trivia_site/apps/users/urls.py
from django.urls import path

from .views import (
    UserDetailView,
    UserRedirectView,
    UserSignUp,
    UserUpdateView,
    ListView,
)

app_name = "users"
urlpatterns = [
    path("signup/", view=UserSignUp.as_view(), name="signup"),
    path("redirect/", view=UserRedirectView.as_view(), name="redirect"),
    path("update/", view=UserUpdateView.as_view(), name="update"),
    path("<str:username>/", view=UserDetailView.as_view(), name="detail"),
    path("me", view=UserDetailView.as_view(), name="my-profile"),
    path("", view=ListView.as_view(), name="list"),
]

trivia_site/trivia_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('questions/', include('apps.questions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # https://docs.djangoproject.com/en/4.2/howto/static-files/#serving-uploaded-files-in-development

if 'debug_toolbar' in settings.INSTALLED_APPS:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

trivia_site/apps/users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import CharField
from django.urls import reverse


class User(AbstractUser):
    """
    Create a custom User class.
    - Not all users have a first and last name, so use a single name field
    - Users should be able to log in with their email, so make it unique
    """
    name = CharField(max_length=255)
    email = models.EmailField('Email address', unique=True)
    avatar = models.ImageField(upload_to='avatars', blank=True, null=True)

    USERNAME_FIELD = 'email'                # Log in with email (instead of username)
    REQUIRED_FIELDS = ['name', 'username']  # Require these when creating a superuser

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.
        """
        return reverse("users:detail", kwargs={"username": self.username})

    @property
    def avatar_url(self):
        if self.avatar:
            return self.avatar.url
        return settings.STATIC_URL + 'images/avatar.png'

trivia_site/apps/users/forms.py
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model
from django.core.files.images import get_image_dimensions
from django.forms import forms

User = get_user_model()


class UserChangeForm(auth_forms.UserChangeForm):
    password = None

    class Meta(auth_forms.UserChangeForm.Meta):
        model = User
        fields = ("name", "email", "avatar")

    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']

        if not avatar:
            return avatar
        try:
            w, h = get_image_dimensions(avatar)

            # validate dimensions
            max_width = max_height = 1000
            if w > max_width or h > max_height:
                raise forms.ValidationError(
                    'Please use an image that is '
                    '%s x %s pixels or smaller.' % (max_width, max_height))

            # validate content type
            main, sub = avatar.content_type.split('/')
            if not (main == 'image' and sub in ['jpeg', 'pjpeg', 'gif', 'png']):
                raise forms.ValidationError('Please use a JPEG, '
                                            'GIF or PNG image.')

            # validate file size
            max_k = 1000
            if len(avatar) > (max_k * 1024):
                raise forms.ValidationError(
                    f'Avatar file size may not exceed {max_k}k.')

        except AttributeError:
            """
            Handles case when we are updating the user profile
            and do not supply a new avatar
            """
            pass

        return avatar


class UserCreationForm(auth_forms.UserCreationForm):
    class Meta(auth_forms.UserCreationForm.Meta):
        model = User
        fields = ("username", "name", "email",)

trivia_site/apps/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.decorators.http import require_GET
from django.views.generic import DetailView, RedirectView, UpdateView, CreateView

from .forms import UserCreationForm, UserChangeForm

User = get_user_model()


class UserSignUp(CreateView):
    success_url = reverse_lazy('index')
    template_name = 'users/signup.html'
    form_class = UserCreationForm

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(self.request, messages.SUCCESS, f"Signup success!")
        login(self.request, self.object)
        return response


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_object(self, *args, **kwargs):
        if "username" not in self.kwargs:
            return User.objects.get(username=self.request.user.username)
        else:
            return super().get_object(*args, **kwargs)


class UserUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserChangeForm

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, "Your info was updated")
        return super().form_valid(form)


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("index")


@require_GET
@login_required
def list_view(request):
    if request.user.is_staff:
        users = User.objects.all()
    else:
        users = User.objects.filter(is_staff=False)
    context = {"users": users}
    return render(request, "users/user_list.html", context=context)


class ListView(LoginRequiredMixin, View):  # Same functionality as list_view()
    def get(self, request):
        if request.user.is_staff:
            users = User.objects.all()
        else:
            users = User.objects.filter(is_staff=False)
        context = {"users": users}
        return render(request, "users/user_list.html", context=context)

trivia_site/templates/users/signup.html
{% extends 'base.html' %}
{% load bulma_tags %}

{% block title %}Sign Up{% endblock %}

{% block bodyclass %}has-background-light{% endblock %}

{% block content %}

<div class="box p-6">
  <h1 class="title">Sign up</h1>
  <form class="signup" method="POST" action="{% url 'users:signup' %}">
    {% csrf_token %}
    {{ form|bulma }}
    <div class="buttons">
      <button class="button is-primary" type="submit">Sign up</button>
    </div>
  </form>
</div>
<div class="block ml-6">
  Have an account?
  <a class="is-secondary" href="{% url 'login' %}">Log in</a>
</div>
{% endblock %}

trivia_site/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ object.name }}{% endblock %}
{% block bodyclass %}has-background-light{% endblock %}

{% block content %}
<div class="box p-6">
  <h2>User profile</h2>

  <div class="is-flex">
    <figure class="image is-128x128 ml-2 mt-5 is-rounded">
      <img class="is-rounded" src="{{ user.avatar_url }}">
    </figure>
    <div class="block ml-3">
      {% include "users/partials/user_field.html" with label="Username" value=object.username %}
      {% include "users/partials/user_field.html" with label="Name" value=object.name %}
      {% include "users/partials/user_field.html" with label="Email" value=object.email %}
    </div>
  </div>

  {% if object == user %}
  <div class="control">
    <a class="button is-primary" href="{% url 'users:update' %}" role="button">Edit</a>
  </div>
  {% endif %}


</div>
{% endblock %}

trivia_site/templates/users/user_form.html
{% extends "base.html" %}
{% load bulma_tags %}

{% block bodyclass %}has-background-light{% endblock %}

{% block title %}{{ user.name }}{% endblock %}

{% block content %}
<div class="box p-6">
<h2>Test profile</h2>
  <p class="subtitle">{{ user.username }}</p>
<form class="form-horizontal" method="post" action="{% url 'users:update' %}" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|bulma_horizontal }}
  {% include "users/partials/image_upload.html" %}
  <div class="field">
    <a class="button" href="{% url 'users:my-profile' %}">Cancel</a>
    <button type="submit" class="button is-primary">Update</button>
  </div>
  <input type="hidden" name="next" value="{{ next }}"/>
</form>
</div>
{% endblock %}

{% block page_js %}
<script>
$(document).ready(function(){

  // Replace the default image picker from form with the custom one in users/partials/image_upload.html

  const to_replace = $("label.file-label")[0];
  $(to_replace).remove();

  // Update filename after choosing a file
  // See: https://bulma.io/documentation/form/file/#javascript

  const fileInput = $('#better-image-field input[type=file]')[0];

  fileInput.onchange = () => {
    if (fileInput.files.length > 0) {
      const fileNameField = $('#better-image-field .file-name')[0];
      fileNameField.textContent = fileInput.files[0].name;
    }
  }
});
</script>

});
{% endblock %}

trivia_site/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ object.name }}{% endblock %}
{% block bodyclass %}has-background-light{% endblock %}

{% block content %}
<div class="box p-6">
  <h2>Users</h2>
<!--  <pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre>-->
  <ul>
    {% for u in users %}
    <li>
      <a href="{{ u.get_absolute_url }}">{{ u.name }}</a>
      {{ u.prop|last }}
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}