trivia_site/apps/questions/urls.py
from django.urls import path

from .views import (
    answer_view,
    complete,
    question_view,
    question_update,
    next_question,
    new_game,
)

app_name = "questions"
urlpatterns = [
    path("new/", view=new_game, name="new"),
    path("complete/", view=complete, name="complete"),
    path("question/", view=next_question, name="question"),
    path("question/<int:pk>/", view=question_view, name="question"),
    path("question/<int:pk>/update/", view=question_update, name="update"),
    path("question/<int:question_pk>/choice/<int:choice_pk>", view=answer_view, name="answer"),
]

trivia_site/trivia_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('questions/', include('apps.questions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # https://docs.djangoproject.com/en/4.2/howto/static-files/#serving-uploaded-files-in-development

if 'debug_toolbar' in settings.INSTALLED_APPS:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

trivia_site/apps/questions/examples/models.py
"""
Example usage of models.

Lines 11 - 25 of this code are just for configuring Django
so that you can run this file as a stand-alone script.

You can also run the examples by running:
  $ python manage.py shell (to start a Django-configured shell)
and then copying and pasting the examples into the shell
"""
import os
import sys
from pathlib import Path


# Make sure Python looks in your trivia_site directory when searching for modules
TRIVIA_SITE_DIR = Path(__file__).resolve().parent.parent.parent.parent
sys.path.append(str(TRIVIA_SITE_DIR))

# Let Django know where to find your settings
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'trivia_project.settings.local')

# Configure Django so your models can be used
import django
django.setup()

# ------------ END of Django setup ----------------

# Import your models
from apps.questions.models import *
# If your IDE gives you an error here:
#   In PyCharm, mark the trivia_site folder as a source root
#   In VS Code, in the Pylance settings, add the trivia_site folder to the extra paths to search: https://stackoverflow.com/a/64103291


# Need to clean up test data from db (normally you would use a separate test db)
last_pk = Question.objects.last().pk  # save the last question's id so we can delete anything created afterwards

# ____________ CREATING OBJECTS ____________

# Create an object without saving to the database (manual save)
q = Question(text="What does ORM stand for?")  # Initialize some fields
q.details = "Hint: you use it to query the database in Python"  # Edit a field
q.difficulty = Question.Difficulty.EASY  # Set a Choice field from an Enum
q.save()  # Save to the db

c1 = Choice(question=q, text="One Radical Magic").save()  # Create related object
c2 = Choice(question=q, text="Object Relational Mapping", is_correct=True).save()

# Create an object and save it to the database
q2 = Question.objects.create(text="What was Django named after?")
Choice.objects.create(question=q2, text="Django Reinhardt (musician)", is_correct=True)
Choice.objects.create(question=q2, text="Django Unchained (movie)", is_correct=False)

# This next bit will make 3 database calls
q3 = Question.objects.create(
    text="What programming language is Django written in?",
    difficulty=Question.Difficulty.MEDIUM,
)  # Create and save to db

q3.difficulty = Question.Difficulty.EASY
q3.save()  # Update object and then save
print(q3.pk)  # Get the object's primary key (id)
q3.delete()  # Delete the object

# ____________ QUERYING THE DATABASE ____________

# Get a single object
try:
    a_question = Question.objects.get(pk=1)  # Try to get an object by ID, can put any filter in here though
    print(a_question)
except Question.DoesNotExist:
    print(f"Question does not exist")
except Question.MultipleObjectsReturned:
    print(f"Multiple questions were returned")

# Get the first/last object
first_q = Question.objects.first()  # Order is pk (default) or what is defined in the model's Meta.ordering
first_created_q = Question.objects.order_by('created_at').first()  # Specify ordering
last_created_q_1 = Question.objects.order_by('created_at').last()
last_created_q_2 = Question.objects.order_by('-created_at').first()  # Reverse order by adding "-" to field
assert last_created_q_1 == last_created_q_2

# Get the set of all objects (returns a QuerySet)
questions = Question.objects.all()

# Get a filtered set of objects
easy_questions = Question.objects.filter(difficulty=Question.Difficulty.EASY)

# Get the number of items in the QuerySet (qs)
print(f"There are {easy_questions.count()} easy questions (out of {questions.count()})")

# Filter based on related objects
qs_without_choices = Question.objects.filter(choices__isnull=True)
print(f"There are {qs_without_choices.count()} questions without choices")

# Can filter based on excluding items
qs_without_answer = Question.objects.exclude(choices__is_correct=True)
print(f"There are {qs_without_answer.count()} questions without answers")

# Bulk update
Question.objects.filter(pk__gt=last_pk).update(details="This is a test question")

# ____________ CLEANUP OF TEST DATA ____________
Question.objects.filter(pk__gt=last_pk).delete()

trivia_site/apps/questions/models.py
from django.db import models
from django.urls import reverse


class Question(models.Model):
    class Difficulty(models.TextChoices):  # Like an Enum
        EASY = "E"
        MEDIUM = "M"
        HARD = "H"

    text = models.CharField('question', max_length=255)
    details = models.TextField(blank=True)
    difficulty = models.CharField(
        max_length=1,                # Char fields require a max length
        choices=Difficulty.choices,  # Creates a dropdown in forms
        blank=True,                  # Not required. If empty, value is ''.
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("questions:question", kwargs={"pk": self.pk})

    def __str__(self):
        return f"Question: {self.text}"

    def __repr__(self):
        string = f"Question ({self.pk}): {self.text}"
        if self.difficulty:
            string += f" - {self.get_difficulty_display()}"  # Display name for a choices field
        return string

    class Meta:
        ordering = ("pk",)                      # This is the default but can be overridden
        verbose_name = "Question"               # This is the default but can be overridden
        verbose_name_plural = "Quiz Questions"  # Shows up in admin navigation


class Choice(models.Model):
    question = models.ForeignKey(  # Define a many-to-one relationship
        Question,                  # There are many choices for every question
        on_delete=models.CASCADE,  # If you delete a question, delete its choices
        related_name="choices"     # Get choices via q.choices (default is q.choice_set)
    )
    text = models.TextField('choice')
    is_correct = models.BooleanField(default=False)
    details = models.TextField(blank=True)

    def __str__(self):
        return f"Choice: {self.text}"

    def __repr__(self):
        return f"Choice ({self.pk}): {self.text}"

trivia_site/apps/questions/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Question, Choice


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ("text", "details")
        widgets = {
            "details": forms.Textarea(attrs={"rows": 3, "class": "textarea"})
        }


# Create a "formset" to update the choices related to a question
# https://docs.djangoproject.com/en/4.2/topics/forms/modelforms/#inline-formsets

ChoiceFormSet = inlineformset_factory(
    parent_model=Question,
    model=Choice,
    fields=('text', 'is_correct', 'details'),
    can_delete=False,
    extra=0,
    min_num=3,
    widgets={
        "text": forms.Textarea(attrs={"rows": 2, "class": "textarea"}),
        "details": forms.Textarea(attrs={"rows": 4, "class": "textarea"}),
    }
)

trivia_site/apps/questions/views.py
from django.contrib import messages
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template import loader

from .forms import ChoiceFormSet, QuestionForm
from .models import Choice, Question


def question_view(request, pk):
    q = get_object_or_404(Question, pk=pk)
    context = {"question": q}
    return render(request, "questions/question.html", context=context)


def answer_view(request, question_pk, choice_pk):
    q = get_object_or_404(Question, pk=question_pk)
    c = get_object_or_404(Choice, question=q, pk=choice_pk)
    context = {"question": q, "selected_choice": c}

    # Update current state
    request.session['last_question_pk'] = q.pk
    if c.is_correct:
        request.session['correct'] += 1

    return render(request, "questions/answer.html", context=context)


def next_question(request):
    last_pk = request.session.get('last_question_pk', 0)

    question = Question.objects.filter(pk__gt=last_pk).first()
    if question:
        return redirect('questions:question', pk=question.pk)
    else:
        return redirect('questions:complete')


def new_game(request):
    request.session['last_question_pk'] = 0
    request.session['correct'] = 0
    request.session['total'] = Question.objects.count()

    return redirect('questions:question')


def complete(request):
    context = {
        "correct": request.session.get('correct', 0),
        "total": request.session.get('total', 0)
    }
    return render(request, "questions/complete.html", context=context)


def question_update(request, pk):
    q = get_object_or_404(Question, pk=pk)

    if request.method == 'POST':
        formset = ChoiceFormSet(request.POST, instance=q)
        form = QuestionForm(request.POST, instance=q)
        if formset.is_valid() and form.is_valid():
            formset.save()
            form.save()
            messages.add_message(request, messages.SUCCESS, "This question was updated")
            return redirect(q.get_absolute_url())
    else:
        formset = ChoiceFormSet(instance=q)
        form = QuestionForm(instance=q)

    context = {"question": form.instance, 'form': form, 'formset': formset}
    return render(request, "questions/question_edit.html", context=context)


def question_view_no_shortcuts(request, pk):
    # instead of get_object_or_404()
    try:
        q = Question.objects.get(pk=pk)
    except Question.DoesNotExist:
        raise Http404('No Question matches the given query.')

    context = {"question": q}

    # instead of render()
    content = loader.render_to_string("questions/question.html", context, request)
    return HttpResponse(content, content_type="text/html", status=200)

trivia_site/templates/questions/answer.html
{% extends 'base.html' %}

{% block bodyclass %}has-background-light{% endblock %}

{% block content %}
<div class="box p-6 has-text-centered is-align-items-center is-flex-direction-column is-flex">
  <h3 class="title">
    {{ question.text|safe }}
    {% if user.is_staff %}
    <a class="icon has-text-info is-size-6" href="{% url 'questions:update' question.pk %}">
        <i class="fas fa-pencil-alt"></i>
    </a>
    {% endif %}
  </h3>
  {% if question.details %}
    <pre class="details block has-text-left">{{ question.details }}</pre>
  {% endif %}
  {% for choice in question.choices.all %}
  <div>
    <a class="question button is-rounded is-unclickable {% if choice.is_correct %}is-success{% elif choice == selected_choice %}is-danger{% else %}is-dark is-outlined{% endif %}">
      {% if choice.is_correct %}
      <span class="icon mr-2">
        <i class="fas fa-check"></i>
      </span>
      {% elif choice == selected_choice %}
      <span class="icon mr-2">
        <i class="fas fa-times"></i>
      </span>
      {% endif %}
      {{ choice.text|linebreaks }}
  </span>
    </a>
    {% if choice == selected_choice %}
    <span class="absolute button is-inverted is-unclickable {% if choice.is_correct %}is-success{% else %}is-danger{% endif %}">
        <span class="icon">
          <i class="fas fa-arrow-left"></i>
        </span>
    </span>
      {% endif %}
    <div class="block mx-6 mt-2 mb-5">
    {{ choice.details|linebreaks }}
    </div>
  </div>
  {% endfor %}
    {% if selected_choice.is_correct %}
      <div class="block has-text-success is-size-4 is-bold">Correct!</div>
    {% else %}
      <div class="block has-text-danger is-size-4 is-bold">Incorrect</div>
    {% endif %}
  <div class="bottom-row is-flex is-justify-content-flex-end">
    <a class="button is-link is-pulled-right" href="{% url 'questions:question' %}">Next</a>
  </div>
</div>
{% endblock %}

trivia_site/templates/questions/complete.html
{% extends 'base.html' %}

{% block bodyclass %}has-background-light{% endblock %}

{% block content %}
<div class="box p-6 has-text-centered">
  <h2>Quiz complete</h2>
  <h3 class="title">
    You got {{ correct }} / {{ total }}
  </h3>
  <div class="block">
      <a class="button is-primary is-size-4" href="{% url 'questions:new' %}">Try again?</a>
  </div>
</div>
{% endblock %}

trivia_site/templates/questions/question.html
{% extends 'base.html' %}

{% block bodyclass %}has-background-light{% endblock %}

{% block content %}
<div class="box p-6 has-text-centered is-align-items-center is-flex-direction-column is-flex">
  <h3 class="title">
    {{ question.text }}
    {% if user.is_staff %}
    <a class="icon has-text-info is-size-6" href="{% url 'questions:update' question.pk %}">
        <i class="fas fa-pencil-alt"></i>
    </a>
    {% endif %}
  </h3>
  {% if question.details %}
  <pre class="details block has-text-left">{{ question.details }}</pre>
  {% endif %}
  {% for choice in question.choices.all %}
  <div class="buttons is-centered">
    <a class="question button is-rounded is-dark is-outlined" href="{% url 'questions:answer' question.pk choice.pk %}">
      {{ choice.text|linebreaks }}
    </a>
  </div>
  {% empty %}
  <div class="block">
    No choices configured
  </div>
  {% endfor %}
</div>
{% endblock %}

trivia_site/templates/questions/question_edit.html
{% extends 'base.html' %}
{% load bulma_tags %}

{% block bodyclass %}has-background-light{% endblock %}

{% block content %}
<div class="box p-6">
  <h2 class="title">Update question {{ question.pk }}</h2>
  <form class="update" method="POST" action="{% url 'questions:update' question.pk %}">
    {% csrf_token %}
    <div class="block p-5">
      {{ form|bulma }}
    </div>
    <h3>Choices</h3>
    <div class="block p-5">
      {{ formset|bulma }}
    </div>
    <div class="buttons">
      <a class="button" href="{{ question.get_absolute_url }}">Cancel</a>
      <button class="button is-primary" type="submit">Update</button>
    </div>
  </form>
</div>
{% endblock %}